/* eslint-disable key-spacing */
export const defaultCalendarTheme = {
  buttonDisabled:         'chili-calendar-button-disabled',
  dateCell:               'chili-calendar-date',
  dateCellActive:         'chili-calendar-date-active',
  dateCellDayOff:         'chili-calendar-date-day-off',
  dateCellDifferentMonth: 'chili-calendar-date-different-month',
  dateCellDisabled:       'chili-calendar-date-disabled',
  dateCellSelected:       'chili-calendar-date-selected',
  dateCellToday:          'chili-calendar-date-today',
  dateRow:                'chili-calendar-date-row',
  dateView:               'chili-calendar-date-view',
  footer:                 'chili-calendar-footer',
  header:                 'chili-calendar-header',
  invalid:                'chili-calendar-invalid',
  monthCell:              'chili-calendar-month-cell',
  monthCellActive:        'chili-calendar-month-cell-active',
  monthCellDisabled:      'chili-calendar-month-cell-disabled',
  monthRow:               'chili-calendar-month-row',
  monthView:              'chili-calendar-month-view',
  nextButton:             'chili-calendar-next-button',
  nextIcon:               'chili-calendar-next-icon',
  prevButton:             'chili-calendar-prev-button',
  prevIcon:               'chili-calendar-prev-icon',
  standalone:             'chili-calendar-standalone',
  standaloneWrapper:       'chili-calendar-standalone-wrapper',
  title:                  'chili-calendar-title',
  titleDisabled:          'chili-calendar-title-disabled',
  weekDay:                'chili-calendar-week-day',
  weekDaysRow:            'chili-calendar-week-days-row',
  wrapper:                'chili-calendar-wrapper',
  wrapperTop:             'chili-calendar-top',
  wrapperRight:           'chili-calendar-right',
  yearCell:               'chili-calendar-year-cell',
  yearCellActive:         'chili-calendar-year-cell-active',
  yearCellDisabled:       'chili-calendar-year-cell-disabled',
  yearCellDifferentDecade:'chili-calendar-year-cell-different-decade',
  yearRow:                'chili-calendar-year-row',
  yearView:               'chili-calendar-year-view',
};
/* eslint-enable key-spacing */
