on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: leda cache
        uses: actions/cache@v1
        id: leda-cache
        with:
          path: node_modules
          key: package-lock=${{ hashFiles('package-lock.json') }}
          restore-keys: package-lock=
      - name: docs cache
        uses: actions/cache@v1
        id: docs-cache
        with:
          path: docs/node_modules
          key: package-lock=${{ hashFiles('docs/package-lock.json') }}
          restore-keys: package-lock=
      - run: npm ci --legacy-peer-deps
        if: steps.leda-cache.outputs.cache-hit != 'true'
      - run: npm ci --legacy-peer-deps --prefix docs
        if: steps.docs-cache.outputs.cache-hit != 'true'
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: package-lock=${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: docs/node_modules
          key: package-lock=${{ hashFiles('docs/package-lock.json')}}
      - run: npm run lint && npm run lint --prefix docs
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: package-lock=${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: docs/node_modules
          key: package-lock=${{ hashFiles('docs/package-lock.json')}}
      - run: npm run test
  tsc:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: package-lock=${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v1
        with:
          path: docs/node_modules
          key: package-lock=${{ hashFiles('docs/package-lock.json')}}
      - run: npm run tsc && npm run tsc:docs