name: Deploy Leda to Main Station
on:
  push:
    branches: ["master"]

jobs:
  # PHASE 1: BUILD THE APPLICATION
  build:
    name: Build Next.js Application
    runs-on: ubuntu-latest # GitHub-hosted Linux VM

    steps:
      # Step: Clone your repo
      - name: Checkout
        uses: actions/checkout@v4

      # Step: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Matches your server
          cache: "npm"

      # Step: Install dependencies
      - name: Install leda dependencies
        run: npm ci

      - name: Build styles
        run: npm run build:css

      - name: Install docs dependencies
        run: npm run ci:docs

      - name: Build
        run: |
          npm run build:docs
          [ -d docs/.next ] || { echo "Error: .next folder not created!"; exit 1; }
          ls -la docs/.next

      - name: Verify artifacts
        run: |
          echo "Files to be uploaded:"
          ls -la docs/.next docs/public
          [ -d docs/.next ] || exit 1

            # Debug: Show full docs directory after build
      - name: Post-build docs directory check
        run: |
          echo "Full docs directory structure:"
          ls -la docs
          echo "Public directory:"
          ls -la docs/public
          echo "Checking required files exist..."
          [ -f docs/.next/BUILD_ID ] || { echo "Error: BUILD_ID missing!"; exit 1; }
          [ -d docs/.next/static ] || { echo "Error: static files missing!"; exit 1; }

      - name: Debug artifact content
        run: |
          echo "docs/.next:"
          ls -R docs/.next || echo "Missing"
          echo "docs/public:"
          ls -R docs/public || echo "Missing"
          echo "dist/styles:"
          ls -R dist/styles || echo "Missing"
          echo "docs/package.json:"
          ls -l docs/package.json || echo "Missing"
          echo "package.json:"
          ls -l package.json || echo "Missing"

      - name: Create artifact archive
        run: |
          mkdir -p artifact-dir/docs
          mkdir -p artifact-dir/dist
          mkdir -p artifact-dir/root

          cp -r docs/.next docs/public docs/package.json docs/package-lock.json artifact-dir/docs/
          cp -r dist/styles artifact-dir/dist/
          cp package.json package-lock.json artifact-dir/root/

          zip -r docs-build.zip artifact-dir

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs-build.zip
          retention-days: 1

  # PHASE 2: DEPLOY TO SERVER
  deploy:
    name: Deploy to Production Server
    needs: build # Waits for build job to complete
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: .

      - name: Upload artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docs-build.zip
          target: /var/www/leda/

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # Your server's IP address
          username: deployer # The user we set up on your server
          key: ${{ secrets.SERVER_SSH_KEY }} # Private key for authentication
          script: |
            APP_DIR=/var/www/leda
            ARTIFACT_NAME=docs-build.zip

            echo "==> Switching to app directory"
            cd $APP_DIR

            echo "==> Unzipping artifact"
            unzip -o $ARTIFACT_NAME

            echo "==> Installing dependencies"
            cd artifact-dir/docs
            npm ci --omit=dev

            echo "==> Restarting PM2 process"
            pm2 restart leda-docs || pm2 start npm --name "leda-docs" -- run start

            echo "✅ Deployment complete"
